version: "3"
services:
  client:
    build: .

  swag:
    image: lscr.io/linuxserver/swag
    cap_add:
      - NET_ADMIN
    env_file:
    - .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=whittakerxyz.duckdns.org
      - VALIDATION=duckdns
      - STAGING=false 
    volumes:
      - /home/ethan/data/swag:/config
      - ./default.conf:/config/nginx/site-confs/default.conf
    ports:
    - 0.0.0.0:3007:443
    restart: unless-stopped